name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avangard_slowed.jpeg
    - assets/blah.jpeg
    - assets/slava_funk.jpeg
    - assets/close_eyes.jpeg
    - assets/metamorphosis.jpeg
    - assets/tokyo_drift.jpeg
    - assets/no_limit.jpeg
    - assets/vox.jpeg
    - assets/corvette.jpeg
    - assets/explore.jpeg
    - assets/collage.jpeg
